# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: ubuntu:trusty

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y software-properties-common python-software-properties
          - add-apt-repository -y ppa:webupd8team/java
          - apt-get install -y oracle-java8-installer
          - chmod +x run-scanner.sh
          - ./run-scanner.sh